import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:"#006830",
    },
    signInHeader:{
        marginVertical:70,
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    backButton:{
        paddingLeft:10,
    },
    userButton:{
        paddingRight:15        
    },
    textBackButton:{
        color:"#FFF",
        fontSize:20,
    },
    textUserName:{
        color:"#FFF",
        fontSize:18,
    },
    textUserMsg:{
        color:"#FFF",
        fontSize:16,
    },
        imgLogo:{
        alignSelf:"center",
        marginTop:-75
    },
    formContainer:{
        flex:1,
        backgroundColor:"#D8E5C3",
        width:"100%",
        height:"100%",
        borderTopLeftRadius:25,
        borderTopRightRadius:25,
        paddingStart:"5%",
        paddingEnd:"5%",
    },
    containerBoxes:{
        height:"85%",
        width:"100%",
        backgroundColor:"#D8E5C3",
        borderTopLeftRadius:25,
        borderTopRightRadius:25,
        paddingStart:"7%",
        paddingEnd:"7%",
        flexWrap:'wrap',
        flexDirection:'row',
    },
    screensButtons:{
        marginTop:-30,
        marginBottom:-30,
        width:'50%',
        height:'40%',
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'row',
    },
    itemsButton:{
        width:120,
        height:120,
        backgroundColor:"#006830",
        borderRadius:13,
        alignItems:'center',
        justifyContent:'center',
        
    },
    itemsTextButton:{
        color:"#FFF",
        marginTop:5
    }
})

export default styles